Eventmanager/urls.py
from django.conf.urls import include, url, handler400, handler403, handler404, handler500
from django.contrib import admin

handler400 = 'events.views.bad_request'
handler403 = 'events.views.permission_denied'
handler404 = 'events.views.page_not_found'
handler500 = 'events.views.server_error'

urlpatterns = [
	url(r'^$', include('events.urls')),
	url(r'^events/', include('events.urls')),
    url(r'^admin/', admin.site.urls),
]

events/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^thanks/(?P<request_type>[0-9]+)/$', views.thanks, name='thanks'),
    url(r'^add/$', views.add, name='add'),
    url(r'^list/$', views.list, name='list'),
    url(r'^new-ticket/$', views.new_ticket, name='new-ticket'),
    url(r'^edit/(?P<event_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^detail/(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^ticket/(?P<ticket_id>[0-9]+)/$', views.ticket, name='ticket'),
    url(r'^delete/(?P<event_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^server_error', views.server_error, name='server_error')
]

events/models.py
from django.db import models

class Event(models.Model):
	event_title = models.CharField(max_length=200)
	event_start_date = models.DateTimeField('date published')
	event_end_date = models.DateTimeField('date published')
	
	def __unicode__(self):
		return "{0} {1} {2} {3}".format(self, self.event_title, self.event_start_date, self.event_end_date)

	def __str__(self):
		return self.event_title
		
class Ticket(models.Model):
	ticket_title = models.CharField(max_length=200)
	ticket_price = models.CharField(max_length=20)
	sale_start_date = models.DateTimeField('date published')
	sale_end_date = models.DateTimeField('date published')
	event = models.ForeignKey(Event, on_delete=models.CASCADE)

	def __unicode__(self):
		return "{0} {1} {2} {3} {4}".format(self.pk, self.ticket_title, self.ticket_price, self.sale_start_date, self.sale_end_date)

	def __str__(self):
		return self.ticket_title

events/forms.py
from django import forms
from .models import Event,Ticket
from datetime import datetime

class BaseForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super(BaseForm, self).__init__(*args, **kwargs)
		#self.fields[ 'event_date' ].input_formats = [ '%m-%d-%Y %H:%M' ]
		for myField in self.fields:
			if 'Date' in self.fields[myField].label:
				self.fields[myField].widget.attrs['class'] = "form-control picker-input"
			else:
				self.fields[myField].widget.attrs['class'] = "form-control"	
			self.fields[myField].widget.attrs['placeholder'] = self.fields[myField].label

class EventForm(BaseForm):
	event_title = forms.CharField(label='Event Title', max_length=100, help_text='Event Title')
	event_start_date = forms.DateTimeField(input_formats=['%m-%d-%Y %H:%M'],label='Event Start Date', help_text='Event Start Date')
	event_end_date = forms.DateTimeField(input_formats=['%m-%d-%Y %H:%M'],label='Event End Date', help_text='Event End Date')

	def save_event(self):
		event_title = self.cleaned_data['event_title']
		event_start_date  = self.cleaned_data['event_start_date'].strftime("%Y-%m-%d %H:%M")
		event_end_date  = self.cleaned_data['event_end_date'].strftime("%Y-%m-%d %H:%M")  
		event = Event(event_title = event_title,event_start_date = event_start_date,event_end_date = event_end_date)
		event.save()
		return event

	def update_event(self, event_id):
		eventDetail = Event.objects.get(id=event_id)
		eventDetail.event_title = self.cleaned_data['event_title']
		eventDetail.event_start_date  = self.cleaned_data['event_start_date'].strftime("%Y-%m-%d %H:%M")
		eventDetail.event_end_date  = self.cleaned_data['event_end_date'].strftime("%Y-%m-%d %H:%M")
		eventDetail.save()
		return eventDetail

class TicketForm(BaseForm):
    ticket_title = forms.CharField(label='Ticket Title',max_length = 250)
    ticket_start_date = forms.DateField(label='Ticket Start Date', required = True)
    ticket_end_date = forms.DateField(label='Ticket End Date', required = True)
    
    def save_ticket(self, event_id):
        ticket_title = self.cleaned_data['ticket_title']
        start_date = self.cleaned_data['ticket_start_date']
        last_date = self.cleaned_data['ticket_end_date']
        ticket = Ticket(ticket_title = ticket_title,start_date = start_date,last_date = last_date,event_id_id = int(event_id))
        ticket.save()
        return ticket		

events/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils.dateparse import parse_date
from django.shortcuts import get_object_or_404, render
from .models import Event, Ticket
from .forms import EventForm, TicketForm
from datetime import datetime
import json
import sys



def _getEventData(eventDetail):
	eventData = {}
	for event in eventDetail:
		eventData = {
			'event_title':event.event_title,
			'event_start_date':event.event_start_date,
			'event_end_date':event.event_end_date
		}
	return eventData

def _getTicketData(ticketDetail):
	ticketData = []
	for ticket in ticketDetail:
			ticketData.append({
				'ticket_id':(ticket.id),
				'ticket_price':ticket.ticket_price, 
				'ticket_title':(ticket.ticket_title),
				'ticket_start_date':ticket.sale_start_date,
				'ticket_end_date':ticket.sale_end_date
			})
	return ticketData	

def index(request):
    return HttpResponseRedirect('/events/list/')

def add(request):
	template = loader.get_template('events/add.html')
	ticketList = []
	
	if request.method == 'POST':
		eventForm = EventForm(request.POST)
		event_start_date = request.POST['event_start_date']
		event_start_date = datetime.strptime(event_start_date, "%m-%d-%Y %H:%M")
		event_end_date = request.POST['event_end_date']
		event_end_date = datetime.strptime(event_end_date, "%m-%d-%Y %H:%M")
		
		context = {'message' : '', 'ticket_list': [], 'eventForm': eventForm}
				
		if eventForm.is_valid():
			ticket_title_list = request.POST.getlist('ticket[][ticket_title]')
			ticket_price_list = request.POST.getlist('ticket[][ticket_price]')
			ticket_start_date_list = request.POST.getlist('ticket[][ticket_start_date]')
			ticket_end_date_list = request.POST.getlist('ticket[][ticket_end_date]')
			
			for index, ticket in enumerate(ticket_title_list):
				ticketList.append({
					'ticket_id': index + 1,
					'ticket_title':ticket,
					'ticket_price':ticket_price_list[index],
					'ticket_start_date':datetime.strptime(ticket_start_date_list[index], '%m-%d-%Y %H:%M'),
					'ticket_end_date':datetime.strptime(ticket_end_date_list[index], '%m-%d-%Y %H:%M')
					})
				
			previousEvent = Event.objects.filter(event_title=request.POST['event_title']).count()
			
			if(previousEvent):
				context = {'message' : 'Event with name - "' + request.POST['event_title'] + '" allready exist', 'ticket_list': ticketList, 'event_form': eventForm}
			else:
				event = eventForm.save_event()
				
				for index, ticket in enumerate(ticket_title_list):
					ticketModel = Ticket(ticket_title=ticket,
						ticket_price=ticket_price_list[index],
						sale_start_date=datetime.strptime(ticket_start_date_list[index], "%m-%d-%Y %H:%M"),
						sale_end_date=datetime.strptime(ticket_end_date_list[index], "%m-%d-%Y %H:%M"),
						event=event)
					ticketModel.save()
			
				return HttpResponseRedirect('/events/thanks/1/')
	else:
		eventForm = EventForm()
		context = {'message' : '', 'ticket_list': [], 'event_form': eventForm}

	return HttpResponse(template.render(context, request))

def edit(request, event_id):
	eventDetail = Event.objects.filter(id=event_id)
	ticketDetail = Ticket.objects.filter(event_id=event_id)
	ticketList = []

	if (Event.objects.filter(id=event_id).count()) != 1:
		return render(request, 'events/page-not-found.html', {})

	if request.method == 'POST':
			ticket_title_list = request.POST.getlist('ticket[][ticket_title]')
			ticket_price_list = request.POST.getlist('ticket[][ticket_price]')
			ticket_start_date_list = request.POST.getlist('ticket[][ticket_start_date]')
			ticket_end_date_list = request.POST.getlist('ticket[][ticket_end_date]')

			for index, ticket in enumerate(ticket_title_list):
				ticketList.append({
					'ticket_title':ticket,
					'ticket_price':ticket_price_list[index],
					'sale_start_date':datetime.strptime(ticket_start_date_list[index], '%m-%d-%Y %H:%M'),
					'sale_end_date':datetime.strptime(ticket_end_date_list[index], '%m-%d-%Y %H:%M')
				})

			event_title = request.POST.get('event_title',"")
			event_start_date =  request.POST.get('event_start_date', "")
			event_start_date = datetime.strptime(event_start_date, '%m-%d-%Y %H:%M')
			event_end_date =  request.POST.get('event_end_date', "")
			event_end_date = datetime.strptime(event_end_date, '%m-%d-%Y %H:%M')

			eventRow = Event.objects.get(id=event_id)

			if eventRow.event_title != event_title:
				previousEvent = Event.objects.filter(event_title=request.POST.get('event_title',"")).exclude(id=event_id).count()
				if(previousEvent):
					eventData = _getEventData(eventDetail)
					ticketList = _getTicketData(ticketDetail)
					eventForm = EventForm(initial=eventData)
					ticketForm = TicketForm()
					context = {'message' : 'Event with name -"' + request.POST['event_title'] + '" allready exist', 'event_id': event_id, 'ticket_list': ticketList, 'event_form': eventForm,  'event_data': eventData}
					return render(request, 'events/edit.html', context)	
					
			eventRow.event_title = event_title
			eventRow.event_start_date  = event_start_date
			eventRow.event_end_date  = event_end_date
			eventRow.save()
			
			# Clear previous tickets
			if Event.objects.filter(id=event_id).count():
				ticketDetail.delete()
			
			if ticket_title_list:
				for index, ticket in enumerate(ticket_title_list):
						ticketModel = Ticket(ticket_title=ticket,
							ticket_price=ticket_price_list[index],
							sale_start_date=datetime.strptime(ticket_start_date_list[index], "%m-%d-%Y %H:%M"),
							sale_end_date=datetime.strptime(ticket_end_date_list[index], "%m-%d-%Y %H:%M"),
							event=eventRow)
						ticketModel.save()
			
			return HttpResponseRedirect('/events/thanks/2/')
	else:		
		eventData = _getEventData(eventDetail)
		ticketList = _getTicketData(ticketDetail)
		
		eventForm = EventForm(initial=eventData)
		ticketForm = TicketForm()
		context = {'message' : '', 'event_id': event_id, 'ticket_list': ticketList, 'event_data': eventData, 'event_form': eventForm, 'ticket_form':ticketForm}
		return render(request, 'events/edit.html', context)	


def list(request):
	context = {'event_list' : Event.objects.all()}
	return render(request, 'events/list.html', context)

def detail(request, event_id):
	context = {'event_detail' : Event.objects.filter(id=event_id), 'ticket_detail': Ticket.objects.filter(event_id=event_id)}
	return render(request, 'events/detail.html', context)

def delete(request, event_id):
	event = Event.objects.filter(id=event_id)
	event.delete()
	return HttpResponseRedirect('/events/list/')


def thanks(request, request_type):
	if int(request_type) == 1 :
		context = {'message' : 'Event has been created'}
	else:
		context = {'message' : 'Event has been updated'}
	return render(request, 'events/thanks.html', context)

def ticket(request, ticket_id):
	context = {'ticket_id' : ticket_id}
	return render(request, 'events/ticket.html', context)		

def bad_request(request):
	return render(request, 'events/bad-request.html', {})

def permission_denied(request):
	return render(request, 'events/permission-denied.html', {})

def page_not_found(request):
	return render(request, 'events/page-not-found.html', {})		

def server_error(request):
	return render(request, 'events/server-error.html', {})

def new_ticket(request):
	ticketForm = TicketForm()
	context = {'message' : '', 'ticketForm': ticketForm}
	return render(request, 'events/ticket-bkp.html', context)	

events/templates/events/add-bkp.html
{% extends 'events/base.html' %}

{% block content %}
<div class="panel panel-default">
  	<div class="panel-body">
		<form action="{% url 'add' %}" method="post">
			{% csrf_token %}
			<div class="form-group">
				<h3><i class="fa fa-bookmark" aria-hidden="true"></i> Event Detail </h3>
			</div>
			<hr/>
			<div class="row">
				<div class="form-group col-md-6">
					 <label for="email">{{ eventForm.event_title.label }}</label>
					{{ eventForm.event_title }}
					<div class="error">{{ eventForm.event_title.errors }}</div>
				</div>
				<div class="form-group col-md-6">
					 <label for="email">{{ eventForm.event_date.label }}</label>
					{{ eventForm.event_date }}
					<div class="error">{{ eventForm.event_date.errors }}</div>
				</div>
			</div>
			<div class="form-group">
				<h3> <i class="fa fa-ticket"></i> Ticket Detail </h3>
			</div>
			<hr/>
			<div id="ticket-section">
				{% include "events/ticket.html" %}
			</div>
			<hr/>
			<input type="submit" class="btn btn-default pull-right" value="Add Event" />
		</form>
	</div>
</div>
<div id="ticket-sample-section" class="hide">
	{% include "events/ticket.html" %}
</div>

<script type="text/javascript">
    $(function () {
        $('.date-picker').datetimepicker({
        	format: "YYYY-MM-DD HH:mm a"
        });
    });
</script>
{% endblock %}

events/templates/events/add.html
{% extends 'events/base.html' %}

{% block content %}
{% load ticket_list_template %}
<div class="panel panel-default">
  	<div class="panel-body">
		<form id="event-form" action="{% url 'add' %}" method="post">
			{% csrf_token %}
			<div class="form-group">
				<h3><i class="fa fa-bookmark" aria-hidden="true"></i> Event Detail </h3>
			</div>
			
			<hr/>
			<div class="row">
				<div class="form-group col-md-4">
					 <label for="email">{{ event_form.event_title.label }}</label>
					{{ event_form.event_title }}
					<div class="error">{{ event_form.event_title.errors }}</div>
				</div>
				<div class="form-group col-md-3">
					 <label for="email">{{ event_form.event_start_date.label }}</label>
					 <div class="input-group date" id="event-start-date-picker">
						{{ event_form.event_start_date }}
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
	                    </span>
					 </div>
					<div class="error">{{ event_form.event_start_date.errors }}</div>
				</div>
				<div class="form-group col-md-3">
					 <label for="email">{{ event_form.event_end_date.label }}</label>
					 <div class="input-group date" id="event-end-date-picker">
						{{ event_form.event_end_date }}
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
	                    </span>
					 </div>
					<div class="error">{{ event_form.event_end_date.errors }}</div>
				</div>
				<div class="form-group col-md-2">
					<label for="email">&nbsp;</label>
					<div><button id="add-ticket-button" type="button" class="btn btn-primary"  onclick="addTicket()" ><i class="fa fa-plus"></i> Add Ticket</button></div>
				</div>
			</div>
			<div class="form-group">
				<h3> <i class="fa fa-ticket"></i> Ticket Detail </h3>
			</div>
			<hr/>
			<div id="ticket-section">
				{% if ticket_list %}
					{% for ticket in ticket_list %}
						{% ticket_list_template ticket.ticket_id ticket.ticket_title ticket.ticket_price ticket.ticket_start_date ticket.ticket_end_date%}
					{% endfor %}
				{% else %}
					<div align="center" class="initial-message"><b>Ticket Goes Here</b></div>
				{% endif %}		
			</div>
			<hr/>
			<div align="right">
				<button type="button" class="btn btn-primary" onclick="addConfirmation()">
					<i class="fa fa-plus" aria-hidden="true"></i> Add Event
				</button>&nbsp;
				<a href="{% url 'list' %}">
					<button type="button" class="btn btn-warning">
						<i class="fa fa-close" aria-hidden="true"></i> Cancel Event
					</button>
				</a>
			</div>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	$(function () {
		{% if message %}
    		bootbox.alert({
				title: "<h3>Error</h3>",
				message : "<h3>{{ message }}</h3>", 
				
			})
    	{% endif %}

        initializeEventDatePicker();

	    {% if ticket_list %}
	    	$("#add-ticket-button").attr('disabled', false);
			{% for ticket in ticket_list %}
				initializeTicketDatePicker("{{ ticket.ticket_id }}", moment("{{ ticket.ticket_start_date|date:'m-d-Y h:i A' }}", "MM-DD-YYYY hh:mm A"), moment($("#id_event_end_date").val(), "MM-DD-YYYY hh:mm A"));
			{% endfor %}
		{% endif %}	
    });
</script>
{% endblock %}

events/templates/events/bad-request.html
{% extends 'events/base.html' %}

{% block content %}
	<div class="panel panel-default">
	  	<div class="panel-body" align="center" style="margin-top: 100px;height: 200px">
	  		<h1>Bad Request</h1>
	  		<div class="row"  align="left" style="margin-top:80px;">
				<div class="col-md-10">&nbsp;</div> 
				<div class="col-md-2">
					<button type="button" class="btn btn-primary pull-right"><a href="{% url 'list' %}"><i class="fa fa-list" aria-hidden="true"></i> Go To List</a></button>
				</div> 
			</div>
	  	</div>
  	</div>
{% endblock %}

events/templates/events/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Event Manager</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/css/bootstrap-datetimepicker.css' rel='stylesheet' type='text/css'>
        <link href="//cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/jquery.datetimepicker.css" type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/js/bootstrap-datetimepicker.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
        <script type="text/javascript" src="{% static 'script/main.js' %}"></script>
    </head>
    <body>
        <div class="page-header" align="center">
            <h2>Event Manager</h2>
        </div>

        <div class="content container">
            {% block content %}
            {% endblock %}
        </div>

        <div class="modal fade" id="alertModel" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title" id="alert-modal-title">Alert</h4>
                </div>
                <div class="modal-body">
                  <p id="alert-modal-body">Message</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
              
            </div>
          </div>

          <div class="modal fade" id="confirmationModel" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                  <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
              
            </div>
          </div>
    </body>
</html>

events/templates/events/detail.html
{% extends 'events/base.html' %}

{% block content %}
<table class="table table-bordered">
	<tr>
		<td colspan="4">
			<button type="button" class="btn btn-primary pull-right">
				<a href="{% url 'list' %}">
					<i class="fa fa-arrow-left" aria-hidden="true"></i> Back
				</a>
			</button>
		</td>
	</tr>
	{% for event in event_detail %}
		<tr>
			<th>Event Title</th>
			<td>{{ event.event_title }}</td>
		</tr>
		<tr>
			<th>Event Date</th>
			<td><span class="label label-primary">{{ event.event_start_date|date:"M,d Y h:i A" }}</span> - <span class="label label-primary">{{ event.event_end_date|date:"M,d Y h:i A" }}</span> </td>
		</tr>
	{% endfor %}
		<tr class="sub-title"><th colspan="2"> Ticket Detail </th></tr>
		<tr>
			<td colspan="2">
				<table class="table">
					<thead>
						<tr>
							<th>Ticket Title</th>
							<th>Ticket Price($)</th>
							<th>Sale Start Dates</th>
							<th>Sale End Date</th>
						</tr>
					</thead>	
					{% if ticket_detail %}
						{% for ticket in ticket_detail %}
							<tr>
								<td>{{ ticket.ticket_title }}</td>
								<td>{{ ticket.ticket_price }}</td>
								<td><span class="label label-primary">{{ ticket.sale_start_date|date:"M,d Y h:i A" }}</span></td>
								<td><span class="label label-primary">{{ ticket.sale_end_date|date:"M,d Y h:i A" }}</span></td>
							</tr>
						{% endfor %}
					{% else %}
						<tr><td colspan="3"><div align="center"><b>No Ticket Found</b></div></td></tr>
					{% endif %}	
				</table>
			</td>
		</tr>	
</table>
{% endblock %}

events/templates/events/edit.html
{% extends 'events/base.html' %}

{% block content %}
{% load ticket_list_template %}
<div class="panel panel-default">
  	<div class="panel-body">
		<form id="event-form" action="{% url 'edit' event_id %}" method="post">
			{% csrf_token %}
			<div class="form-group">
				<h3><i class="fa fa-bookmark" aria-hidden="true"></i> Event Detail </h3>
				<div class="error expired-event-msg hide">You can't edit this event as it has been expired</div>
			</div>
			<hr/>
			<div class="row">
				<div class="form-group col-md-4">
					<label for="email">Event Title</label>
					<input type="text" class="form-control title" id="id_event_title" name="event_title" required="" placeholder="Ticket Title" value="{{ event_data.event_title }}"/>
					<div class="error"></div>
				</div>
				<div class="form-group col-md-3">
					<label for="email">Event Start Date</label>
					<div class='input-group date' id="event-start-date-picker">
						<input type="text" class="form-control date-picker picker-input" id="id_event_start_date" name="event_start_date" required="" value="{{ event_data.event_start_date|date:'m-d-Y H:i' }}"/>
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
	                    </span>
                    </div>
					<div class="error"></div>
				</div>
				<div class="form-group col-md-3">
					<label for="email">Event End Date</label>
					<div class='input-group date' id="event-end-date-picker">
						<input type="text" class="form-control date-picker picker-input" id="id_event_end_date" name="event_end_date" required="" value="{{ event_data.event_end_date|date:'m-d-Y H:i' }}"/>
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
	                    </span>
                    </div>
					<div class="error"></div>
				</div>
				<div class="form-group col-md-2">
					<label for="email">&nbsp;</label>
					<div><button id="add-ticket-button" type="button" class="btn btn-primary add-button"  onclick="addTicket()" ><i class="fa fa-plus"></i> Add Ticket</button></div>
				</div>
			</div>
			<div class="form-group">
				<h3> <i class="fa fa-ticket"></i> Ticket Detail </h3>
			</div>
			<hr/>
			<div id="ticket-section">
				{% if ticket_list %}
					{% for ticket in ticket_list %}
						{% ticket_list_template ticket.ticket_id ticket.ticket_title ticket.ticket_price ticket.ticket_start_date ticket.ticket_end_date%}
					{% endfor %}
				{% else %}
					<div align="center" class="initial-message"><b>Ticket Goes Here</b></div>
				{% endif %}		
			</div>
			<hr/>
			<div align="right">
				<button type="button" class="btn btn-primary update-button" onclick="editConfirmation()">
					<i class="fa fa-plus" aria-hidden="true"></i> Update Event
				</button>&nbsp;
				<a href="{% url 'list' %}">
					<button type="button" class="btn btn-warning">
						<i class="fa fa-arrow-left" aria-hidden="true"></i> Back 
					</button>
				</a>
			</div>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	
    $(function () {
    	{% if message %}
    		bootbox.alert({
				title: "<h3>Error</h3>",
				message : "<h3>{{ message }}</h3>", 
				
			})
    	{% endif %}
    	var eventStartDate = moment("{{ event_data.event_start_date|date:'m-d-Y h:i A' }}", "MM-DD-YYYY hh:mm A");
    	var eventEndDate = moment("{{ event_data.event_end_date|date:'m-d-Y h:i A' }}", "MM-DD-YYYY hh:mm A");

    	if (moment() <= eventStartDate) {
    		$("#id_event_start_date").attr('readonly', true);
    	}	

    	if (moment() < eventEndDate) {
	        initializeEventDatePicker(eventStartDate, eventEndDate);

		    if($("#id_event_end_date").val()) {
			    {% if ticket_list %}
					{% for ticket in ticket_list %}
						initializeTicketDatePicker("{{ ticket.ticket_id }}", moment("{{ ticket.ticket_start_date|date:'m-d-Y h:i A' }}", "MM-DD-YYYY hh:mm A"), eventEndDate);
					{% endfor %}
				{% endif %}		
			}	
		} else {
			$('.title').attr('readonly', true);
			$("#id_event_start_date").attr('readonly', true);
			$("#id_event_end_date").attr('readonly', true);
			$('.ticket-date-picker').attr('readonly', true);
			$('.add-button').attr('disabled', true);
			$('.delete-button').attr('disabled', true);
			$('.update-button').attr('disabled', true);
			if ($("#id_event_date").val())
				$('.expired-event-msg').removeClass('hide');
		}
    });
</script>
{% endblock %}

events/templates/events/index.html
<html>
	<header></header>
	<body>
		Welcome to {{ from_page }}
	</body>
</html>